### PR TITLE
Update things.

### PR DESCRIPTION
**Pull request by joho**
Important things.

### CODE REVIEW

**Comment by navitronic** [comment]
:-1: This PR should update the minified file too.

We can't expect users of 2012 javascript to have their own build pipelines. How would that integrate with their FTP workflow?

**Comment by markdalgleish** [comment]
Agreed. @joho if you need help with this, there's a handy section in the readme that documents the build process: https://github.com/markdalgleish/fathom#how-to-build

**Comment by joho** [comment]
Fixed. :shipit: ?

**Comment by markdalgleish** [comment]
Thanks for your support! Keep on jQuerying! :dancer:

**Pull request merged**
